-- admin_rls.sql
-- INSTRUCTIONS: Run this in your Supabase SQL Editor once.
-- This grants super-administrator emails full access to see and approve company registrations
-- while keeping the rest of the companies completely isolated from each other.

-- Note: We check the secure JWT token generated by Supabase during login to guarantee email authenticity.

CREATE POLICY "Super Admins can view all companies" 
  ON public.companies FOR SELECT 
  USING (
    auth.jwt() ->> 'email' IN ('syscompany85@gmail.com', 'osama@syswms.com')
  );

CREATE POLICY "Super Admins can update all companies" 
  ON public.companies FOR UPDATE 
  USING (
    auth.jwt() ->> 'email' IN ('syscompany85@gmail.com', 'osama@syswms.com')
  );
