-- Supabase PostgreSQL Schema for SYS STD Pro

-- 0. Companies (Colleges/Admins) Table
CREATE TABLE IF NOT EXISTS public.companies (
    id uuid references auth.users not null primary key,
    company_code text unique not null,
    company_name text not null,
    university_name text,
    department_name text,
    full_name text not null,
    position text,
    phone text,
    email text unique not null,
    status text default 'pending',
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 1. Students Table
CREATE TABLE IF NOT EXISTS public.students (
    student_id text primary key, -- e.g. std00xx
    student_name text not null,
    grade text,
    academic_year text,
    photo_url text,
    reg_date timestamp with time zone default timezone('utc'::text, now()),
    status text default 'Active'
);

-- 2. Professors Table
CREATE TABLE IF NOT EXISTS public.professors (
    prof_id text primary key, -- e.g. prof001
    prof_name text not null,
    subject text,
    teaching_stage text,
    photo_url text,
    reg_date timestamp with time zone default timezone('utc'::text, now()),
    status text default 'Active'
);

-- 3. Attendance Table
CREATE TABLE IF NOT EXISTS public.attendance (
    id bigint generated by default as identity primary key,
    student_id text references public.students(student_id) on delete cascade,
    student_name text not null,
    prof_id text references public.professors(prof_id) on delete set null,
    prof_name text,
    date date not null,
    subject text,
    grade text,
    status text,
    check_in text,
    check_out text,
    notes text,
    unique(student_id, date, subject, prof_id)
);

-- 4. Student History Table
CREATE TABLE IF NOT EXISTS public.student_history (
    id bigint generated by default as identity primary key,
    student_id text references public.students(student_id) on delete cascade,
    student_name text not null,
    academic_year text not null,
    grade text not null,
    status text not null, -- 'Passed', 'Failed', 'Graduated'
    recorded_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
    id bigint primary key check (id = 1),
    language text default 'ar',
    theme text default 'light',
    font_family text default 'Arial',
    font_scale numeric default 1.0,
    accent_color text default '#F49000'
);

-- Insert original settings row
INSERT INTO public.settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- Security: Enable Row Level Security (RLS)
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.professors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Note: For a local or trusted company application, you can allow fully public access,
-- or map it to Supabase Auth. Since the original app used a simple login table, 
-- we will allow anon read/write for now, but you should restrict this in production!

-- Allow public access for demonstration (Remove these and use authenticated policies in production)
CREATE POLICY "Allow public all on companies" ON public.companies FOR ALL USING (true);
CREATE POLICY "Allow public all on students" ON public.students FOR ALL USING (true);
CREATE POLICY "Allow public all on student_history" ON public.student_history FOR ALL USING (true);
CREATE POLICY "Allow public all on professors" ON public.professors FOR ALL USING (true);
CREATE POLICY "Allow public all on attendance" ON public.attendance FOR ALL USING (true);
CREATE POLICY "Allow public all on settings" ON public.settings FOR ALL USING (true);

-- 6. Subject Assignments Table
CREATE TABLE IF NOT EXISTS public.subject_assignments (
    id bigint generated by default as identity primary key,
    stage_name text not null,
    subject_name text not null,
    prof_id text references public.professors(prof_id) on delete set null,
    unique(stage_name, subject_name)
);

ALTER TABLE public.subject_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public all on subject_assignments" ON public.subject_assignments FOR ALL USING (true);
