-- Supabase PostgreSQL Schema for SYS WMS Pro

-- 1. Workers Table
CREATE TABLE IF NOT EXISTS public.workers (
    id bigint generated by default as identity primary key,
    name text not null,
    position text,
    salary numeric,
    photo_url text,
    reg_date timestamp with time zone default timezone('utc'::text, now()),
    status text default 'Active'
);

-- 2. Attendance Table
CREATE TABLE IF NOT EXISTS public.attendance (
    id bigint generated by default as identity primary key,
    worker_id bigint references public.workers(id) on delete cascade,
    worker_name text not null,
    date date not null,
    status text,
    check_in text,
    check_out text,
    overtime numeric default 0,
    notes text,
    unique(worker_id, date)
);

-- 3. Cash Advance Table
CREATE TABLE IF NOT EXISTS public.cash_advance (
    id bigint generated by default as identity primary key,
    worker_id bigint references public.workers(id) on delete cascade,
    worker_name text not null,
    date date default CURRENT_DATE,
    amount numeric not null,
    reason text,
    status text default 'Pending'
);

-- 4. Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
    id bigint primary key check (id = 1),
    language text default 'ar',
    theme text default 'light',
    font_family text default 'Arial',
    font_scale numeric default 1.0,
    accent_color text default '#F49000'
);

-- Insert original settings row
INSERT INTO public.settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- Security: Enable Row Level Security (RLS)
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_advance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Note: For a local or trusted company application, you can allow fully public access,
-- or map it to Supabase Auth. Since the original app used a simple login table, 
-- we will allow anon read/write for now, but you should restrict this in production!

-- Allow public access for demonstration (Remove these and use authenticated policies in production)
CREATE POLICY "Allow public all on workers" ON public.workers FOR ALL USING (true);
CREATE POLICY "Allow public all on attendance" ON public.attendance FOR ALL USING (true);
CREATE POLICY "Allow public all on cash_advance" ON public.cash_advance FOR ALL USING (true);
CREATE POLICY "Allow public all on settings" ON public.settings FOR ALL USING (true);
