-- Supabase PostgreSQL Schema for SYS STD Pro
-- UNIFIED SCHEMA v2.0 (Colleges instead of Companies)

-- 0. Colleges Table (Formerly Companies)
CREATE TABLE IF NOT EXISTS public.colleges (
    id uuid references auth.users not null primary key,
    college_code text unique not null,
    college_name text not null,
    university_name text,
    department_name text,
    full_name text not null,
    position text,
    phone text,
    email text unique not null,
    status text default 'pending',
    settings jsonb default '{}',
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 1. Students Table
CREATE TABLE IF NOT EXISTS public.students (
    student_id text primary key, -- e.g. std00xx
    college_id uuid references public.colleges(id) on delete cascade,
    student_name text not null,
    grade text,
    academic_year text,
    photo_url text,
    reg_date timestamp with time zone default timezone('utc'::text, now()),
    status text default 'Active'
);

-- 2. Professors Table
CREATE TABLE IF NOT EXISTS public.professors (
    prof_id text primary key, -- e.g. prof001
    college_id uuid references public.colleges(id) on delete cascade,
    prof_name text not null,
    subject text,
    teaching_stage text,
    photo_url text,
    reg_date timestamp with time zone default timezone('utc'::text, now()),
    status text default 'Active'
);

-- 3. Attendance Table
CREATE TABLE IF NOT EXISTS public.attendance (
    id bigint generated by default as identity primary key,
    college_id uuid references public.colleges(id) on delete cascade,
    student_id text references public.students(student_id) on delete cascade,
    student_name text not null,
    prof_id text references public.professors(prof_id) on delete set null,
    prof_name text,
    date date not null,
    subject text,
    grade text,
    status text,
    academic_year text,
    check_in text,
    check_out text,
    notes text,
    unique(college_id, student_id, date, subject, prof_id)
);

-- 4. Student History Table
CREATE TABLE IF NOT EXISTS public.student_history (
    id bigint generated by default as identity primary key,
    college_id uuid references public.colleges(id) on delete cascade,
    student_id text references public.students(student_id) on delete cascade,
    student_name text not null,
    academic_year text not null,
    grade text not null,
    status text not null, -- 'Passed', 'Failed', 'Graduated'
    recorded_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
    id bigint primary key check (id = 1),
    language text default 'ar',
    theme text default 'light',
    font_family text default 'Arial',
    font_scale numeric default 1.0,
    accent_color text default '#F49000'
);

-- Insert original settings row
INSERT INTO public.settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- 6. Subject Assignments Table
CREATE TABLE IF NOT EXISTS public.subject_assignments (
    id bigint generated by default as identity primary key,
    college_id uuid references public.colleges(id) on delete cascade,
    stage_name text not null,
    subject_name text not null,
    prof_id text references public.professors(prof_id) on delete set null,
    unique(college_id, stage_name, subject_name)
);

-- Security: Enable Row Level Security (RLS)
ALTER TABLE public.colleges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.professors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subject_assignments ENABLE ROW LEVEL SECURITY;

-- Allow public access for demonstration (Restrict this in production!)
CREATE POLICY "Allow public all on colleges" ON public.colleges FOR ALL USING (true);
CREATE POLICY "Allow public all on students" ON public.students FOR ALL USING (true);
CREATE POLICY "Allow public all on student_history" ON public.student_history FOR ALL USING (true);
CREATE POLICY "Allow public all on professors" ON public.professors FOR ALL USING (true);
CREATE POLICY "Allow public all on attendance" ON public.attendance FOR ALL USING (true);
CREATE POLICY "Allow public all on settings" ON public.settings FOR ALL USING (true);
CREATE POLICY "Allow public all on subject_assignments" ON public.subject_assignments FOR ALL USING (true);
